language: go
go:
  - 1.7
before_install:
  - openssl aes-256-cbc -K $encrypted_383bc2ea2d21_key -iv $encrypted_383bc2ea2d21_iv -in deploy_key.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - git clone git@github.com:KoharaKazuya/KoharaKazuya.github.io.git public
install: if [ ! -e "$HOME/bin/hugo" ]; then mkdir -p "$HOME/bin" && cd "$HOME/bin" && wget -O - 'https://github.com/spf13/hugo/releases/download/v0.16/hugo_0.16_linux-64bit.tgz' | tar xfz -; fi
script:
  - cd $TRAVIS_BUILD_DIR
  - $HOME/bin/hugo
after_success:
  - cd public
  - git add --all
  - git commit --message 'Auto updated by TravisCI'
  - git push -f origin
cache:
  directories:
    - "$HOME/bin"
env:
  global:
    - GIT_COMMITTER_NAME=KoharaKazuya
    - GIT_COMMITTER_EMAIL=reflect.results@gmail.com
    - GIT_AUTHOR_NAME=KoharaKazuya
    - GIT_AUTHOR_EMAIL=reflect.results@gmail.com
